twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        'assets/static/images': images
        'assets/css': styles
    globals:
        ga_tracking: 'UA-xxxxx-x'
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
