magephp:
#  log_dir: ./tools/ReleaseManager/logs
#  log_limit: 10
  custom_tasks:
    - 'App\Tools\MageTools\Task\Release\Zip\PrepareTask'
    - 'App\Tools\MageTools\Task\Symfony\DatabaseBackUpTask'
    - 'App\Tools\MageTools\Task\Symfony\PlatformReleaseTask'
    - 'App\Tools\MageTools\Task\Yarn\BuildTask'
    - 'App\Tools\MageTools\Task\Yarn\InstallTask'
  environments:
    release:
      tar_create_path: tar
      tar_extract_path: tar
      user: avbapt
      from: ./
      releases: 4
      host_path: /home3/avbapt/releases/production
      exclude:
        - ./var/cache/*
        - ./var/log/*
        - ./tools
        - ./horizon-ui-chakra/*
        - ./vendor/netgen/**/tests
      hosts:
        - 192.185.5.34:2222
      pre-deploy:
      on-deploy:
      on-release:
        - fs/copy: { from: '/home3/avbapt/releases/production/.env.local.php', to: '/home3/avbapt/releases/production/current/.env.local.php' }
        - fs/copy: { from: '/home3/avbapt/releases/production/current/public/build/*', to: '/home3/avbapt/public_html/build', flags: '-prf' }
        - fs/copy: { from: '/home3/avbapt/releases/production/current/public/bundles/*', to: '/home3/avbapt/public_html/bundles', flags: '-prf' }
        - exec: { cmd: '/home3/avbapt/releases/production/current/bin/console doctrine:migrations:migrate --env=prod --no-interaction', desc: 'Run Doctrine Migrations if needed.'}
      post-deploy:
#        - composer/install: { flags: '--no-scripts' }
#        - yarn/install
#        - yarn/build
#        - symfony/assets-install: { env: 'dev', target: 'public' }
    production:
#      user: app
      branch: main
      from: ./
#      host_path: /var/www/myapp
      releases: 4
      exclude:
        - ./var/*
        - ./horizon-ui-chakra/*
        - ./tools/*
        - '*.local*'
#        - ./var/cache/*
#        - ./var/log/*
#        - ./web/app_dev.php
#      hosts:
#        - webserver1
#        - webserver2
#        - webserver3
      # Runs on Local
      pre-deploy:
        - fs/remove: {file: './public/bundles', flags: '-Rf'}
        - fs/remove: {file: './public/build', flags: '-Rf'}
        - fs/remove: {file: './vendor', flags: '-Rf'}
        - composer/install: { flags: '--no-dev --no-scripts' }
        - composer/dump-autoload
        - yarn/install
        - yarn/build: { buildType: 'build' }
        - symfony/assets-install: { env: 'prod', target: 'public' }
        - release/zip/prepare
      # Runs on all Hosts
      on-deploy:
#        - symfony/cache-warmup: { env: 'dev' }
#        - symfony/assets-install: { env: 'dev' }
      # Runs on all Hosts
      on-release:
        # GH Release Commands here
      # Runs on all Hosts
      post-release:
      # Runs on Local
      post-deploy:
        - fs/remove: { file: './public/bundles', flags: '-Rf' }
        - fs/remove: { file: './public/build', flags: '-Rf' }
        - fs/remove: { file: './vendor', flags: '-Rf' }
        - composer/install: { flags: '--no-scripts' }
        - yarn/install
        - yarn/build
        - symfony/assets-install: { env: 'dev', target: 'public' }